# SPDX-FileCopyrightText: 2021-present, git-cliff contributors <https://github.com/orhun/git-cliff>
# SPDX-FileCopyrightText: 2025-2026, Elliot Fontaine <yard-godot@elliotfontaine.anonaddy.com>
# SPDX-FileCopyrightText: 2026-present, YARD contributors (see AUTHORS.md)
#
# SPDX-License-Identifier: CC0-1.0

# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
# A Tera template to be rendered as the changelog's header.
# See https://keats.github.io/tera/#getting-started
header = """
<!--
SPDX-FileCopyrightText: 2025-2026, Elliot Fontaine <yard-godot@elliotfontaine.anonaddy.com>
SPDX-FileCopyrightText: 2026-present, YARD contributors (see AUTHORS.md)

SPDX-License-Identifier: CC0-1.0
-->

# Changelog\n
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/2.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/#getting-started
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{%- macro commit_line(commit) -%}
    - {% if commit.breaking %}⚠ {% endif -%}
    {%- if commit.scope %}**{{ commit.scope }}:** {% endif -%}
    {{ commit.breaking_description | default(value=commit.message) | split(pat="\n") | first | upper_first | trim }}\
        {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}
        {% if commit.remote.pr_number %} in \
        [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) \
        {%- endif -%}
{%- endmacro -%}

{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}

{%- set breaking_commits = commits | filter(attribute="breaking", value=true) -%}
{% if breaking_commits | length != 0 %}
    ### ⚠ Breaking Changes
    {% raw %}{% endraw -%}
    {%- for commit in breaking_commits %}
        {{ self::commit_line(commit=commit) }}
    {%- endfor %}
{% endif -%}

{% for group, commits in commits | filter(attribute="merge_commit", value=false) | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% raw %}{% endraw -%}
    {%- for commit in commits %}
        {{ self::commit_line(commit=commit) }}
    {%- endfor %}
{% endfor %}

{%- if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
    ### New Contributors
    {% raw %}{% endraw -%}
{%- endif -%}

{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  - @{{ contributor.username }} made their first contribution
    {%- if contributor.pr_number %} in \
      [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) \
    {%- endif %}
{%- endfor %}\n

{%- if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}{% raw %}\n{% endraw -%}{% endif %}

"""
# A Tera template to be rendered as the changelog's footer.
# See https://keats.github.io/tera/#getting-started
footer = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% for release in releases -%}
    {% if release.version and release.previous and release.previous.version -%}
        [{{ release.version | trim_start_matches(pat="v") }}]: \
            {{ self::remote_url() }}/compare/{{ release.previous.version }}...{{ release.version }}
    {% elif not release.version and release.previous and release.previous.version -%}
        [unreleased]: {{ self::remote_url() }}/compare/{{ release.previous.version }}...HEAD
    {% endif -%}
{% endfor %}
<!-- generated by git-cliff -->
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true

[git]
# Prefix for semantic tags
tag_prefix = "v"
# Ignore pre-release tags
tag_pattern = "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = false
# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = [
    # Remove issue numbers.
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]
# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
commit_parsers = [
    { message = "^(chore|style|refactor|ci|test|docs)(\\(.*\\))?!?:", skip = true },
    { message = "^fix", group = "Fixed" },
    { message = "^[a|A]dd", group = "Added" },
    { message = "^[s|S]upport", group = "Added" },
    { message = "^[a|A]llow", group = "Added" },
    { message = "^[i|I]mprove", group = "Changed" },
    { message = "^[r|R]emove", group = "Removed" },
    { message = "^.*: add", group = "Added" },
    { message = "^.*: support", group = "Added" },
    { message = "^.*: allow", group = "Added" },
    { message = "^.*: improve", group = "Changed" },
    { message = "^.*: fix", group = "Fixed" },
    { message = "^.*: remove", group = "Removed" },
    { message = "^.*: delete", group = "Removed" },
    { message = "^.*", group = "Changed" },
]
# Exclude commits that are not matched by any commit parser.
filter_commits = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "newest"

[output]
file = "CHANGELOG.md"
format = "MD"         # Markdown
