version = 1

# Godot Scenes and Resources
[[annotations]]
path = [
    "addons/yard/**.tscn",
    "addons/yard/**.tres",
    "example/godomon/**.tscn",
    "example/godomon/**.tres",
]
SPDX-FileCopyrightText = [
    "2025-2026, Elliot Fontaine <yard-godot@elliotfontaine.anonaddy.com>",
    "2026-present, YARD contributors (see AUTHORS.md)",
]
SPDX-License-Identifier = "MIT"

# Godot Uncopyrightable Files
[[annotations]]
path = ["project.godot", "**.import", "**.uid", "addons/yard/plugin.cfg"]
SPDX-FileCopyrightText = [
    "2025-2026, Elliot Fontaine <yard-godot@elliotfontaine.anonaddy.com>",
    "2026-present, YARD contributors (see AUTHORS.md)",
]
SPDX-License-Identifier = "CC0-1.0"

# Pull Request Template
[[annotations]]
path = ".github/pull_request_template.md"
precedence = "override"
SPDX-FileCopyrightText = [
    "2025-2026, Elliot Fontaine <yard-godot@elliotfontaine.anonaddy.com>",
    "2026-present, YARD contributors (see AUTHORS.md)",
]
SPDX-License-Identifier = "CC0-1.0"

# Original Art
[[annotations]]
path = [
    "icon.png",
    "icon.svg",
    "addons/yard/editor_only/assets/ui_example.png",
    "addons/yard/editor_only/assets/yard.svg",
    "addons/yard/editor_only/assets/yard_dark.svg",
    "addons/yard/editor_only/assets/yard_light.svg",
    "etc/editor_screenshot.png",
    "etc/featured_asset_store.png",
    "etc/logo_blue.png",
    "etc/logo_white.png",
    "etc/plugin_ui_architecture.png",
    "etc/preview_1.png",
    "etc/preview_2.png",
    "etc/preview_3.png",
    "etc/preview_code_1.png",
]
precedence = "override"
SPDX-FileCopyrightText = [
    "2025-2026, Elliot Fontaine <yard-godot@elliotfontaine.anonaddy.com>",
    "2026-present, YARD contributors (see AUTHORS.md)",
]
SPDX-License-Identifier = "CC0-1.0"

# GitHub Invertocat Icon
[[annotations]]
path = ["addons/yard/editor_only/assets/github_icon.svg"]
SPDX-FileCopyrightText = "2026 GitHub Inc."
SPDX-License-Identifier = "MIT"

# Voxybuns' icons
[[annotations]]
path = [
    "example/godomon/assets/class_icons/atom.svg",
    "example/godomon/assets/class_icons/dragon.svg",
    "example/godomon/assets/class_icons/explosion.svg",
    "example/godomon/assets/class_icons/fire.svg",
    "example/godomon/assets/class_icons/gem.svg",
    "example/godomon/assets/class_icons/magic_wand.svg",
    "example/godomon/assets/class_icons/spiral.svg",
]
SPDX-FileCopyrightText = "2026–present, Valentin Fossati (Voxybuns) and contributors <https://github.com/Voxybuns/at-icons>"
SPDX-License-Identifier = "MIT"

# PrincessPhoenix Fakemons
[[annotations]]
path = [
    "example/godomon/assets/**/Anu.png",
    "example/godomon/assets/**/Baobaraffe.png",
    "example/godomon/assets/**/Baoby.png",
    "example/godomon/assets/**/Cobarett.png",
    "example/godomon/assets/**/Drashimi.png",
    "example/godomon/assets/**/Firomenis.png",
    "example/godomon/assets/**/Hissiorite.png",
    "example/godomon/assets/**/Merlicun.png",
    "example/godomon/assets/**/Nuenflu.png",
    "example/godomon/assets/**/Pythonova.png",
    "example/godomon/assets/**/Tobishimi.png",
    "example/godomon/assets/**/Tsushimi.png",
]
SPDX-FileCopyrightText = "2020-2021, Yvonne (princess-phoenix) <https://www.deviantart.com/princess-phoenix/gallery/40859049/project-freemon>"
SPDX-License-Identifier = "CC0-1.0"


# Magiscarf Fakemons
[[annotations]]
path = [
    "example/godomon/assets/**/Adepht.png",
    "example/godomon/assets/**/Anxiust.png",
    "example/godomon/assets/**/Appalyp.png",
    "example/godomon/assets/**/Asterish.png",
    "example/godomon/assets/**/Avipex.png",
    "example/godomon/assets/**/Beeheave(Electric).png",
    "example/godomon/assets/**/Beeheave(Ground).png",
    "example/godomon/assets/**/Beeheave(Normal).png",
    "example/godomon/assets/**/Blockodile.png",
    "example/godomon/assets/**/Blonk.png",
    "example/godomon/assets/**/Boistaur.png",
    "example/godomon/assets/**/Bombustoad.png",
    "example/godomon/assets/**/Bonfur.png",
    "example/godomon/assets/**/Botanine.png",
    "example/godomon/assets/**/Brayd.png",
    "example/godomon/assets/**/Brewtrid.png",
    "example/godomon/assets/**/Brushle.png",
    "example/godomon/assets/**/Burrub.png",
    "example/godomon/assets/**/Chartail.png",
    "example/godomon/assets/**/Chickite.png",
    "example/godomon/assets/**/Chimbat.png",
    "example/godomon/assets/**/Chromeleon.png",
    "example/godomon/assets/**/Chrycric.png",
    "example/godomon/assets/**/Chryspark.png",
    "example/godomon/assets/**/Chrysurge.png",
    "example/godomon/assets/**/Clodiva.png",
    "example/godomon/assets/**/Clolly.png",
    "example/godomon/assets/**/Clowee.png",
    "example/godomon/assets/**/Colobble.png",
    "example/godomon/assets/**/Colobbus.png",
    "example/godomon/assets/**/Crestaka.png",
    "example/godomon/assets/**/Cretassom.png",
    "example/godomon/assets/**/Crucibat.png",
    "example/godomon/assets/**/Curiust.png",
    "example/godomon/assets/**/Curlusk.png",
    "example/godomon/assets/**/Dampurr.png",
    "example/godomon/assets/**/Dansakoi.png",
    "example/godomon/assets/**/Delugar.png",
    "example/godomon/assets/**/Dialapis.png",
    "example/godomon/assets/**/Dripwirt.png",
    "example/godomon/assets/**/Droopig.png",
    "example/godomon/assets/**/Dustfully.png",
    "example/godomon/assets/**/Dynabit.png",
    "example/godomon/assets/**/Embat.png",
    "example/godomon/assets/**/Enderbirld.png",
    "example/godomon/assets/**/Expunge.png",
    "example/godomon/assets/**/Fangtomask.png",
    "example/godomon/assets/**/Fencival.png",
    "example/godomon/assets/**/Flixtrix.png",
    "example/godomon/assets/**/Flobal.png",
    "example/godomon/assets/**/Flooie.png",
    "example/godomon/assets/**/Forbiddron.png",
    "example/godomon/assets/**/Froll.png",
    "example/godomon/assets/**/Fryrry.png",
    "example/godomon/assets/**/Fumbat.png",
    "example/godomon/assets/**/Gardial.png",
    "example/godomon/assets/**/Gelescent.png",
    "example/godomon/assets/**/Gilactic.png",
    "example/godomon/assets/**/Hivernor.png",
    "example/godomon/assets/**/Hoolihog.png",
    "example/godomon/assets/**/Howliage.png",
    "example/godomon/assets/**/Imagamma.png",
    "example/godomon/assets/**/Impurp.png",
    "example/godomon/assets/**/Industove.png",
    "example/godomon/assets/**/Juncko.png",
    "example/godomon/assets/**/Juraspur.png",
    "example/godomon/assets/**/Kalaxodon.png",
    "example/godomon/assets/**/Kankersaur.png",
    "example/godomon/assets/**/Kankryst.png",
    "example/godomon/assets/**/Kankwart.png",
    "example/godomon/assets/**/Larvalpha.png",
    "example/godomon/assets/**/Leazury.png",
    "example/godomon/assets/**/Littoril.png",
    "example/godomon/assets/**/Lollybog.png",
    "example/godomon/assets/**/Lumaxi.png",
    "example/godomon/assets/**/Lumedi.png",
    "example/godomon/assets/**/Lumini.png",
    "example/godomon/assets/**/Lunapede.png",
    "example/godomon/assets/**/Luxp.png",
    "example/godomon/assets/**/Majestaur.png",
    "example/godomon/assets/**/Mivota.png",
    "example/godomon/assets/**/Mobiusk.png",
    "example/godomon/assets/**/Mondrog.png",
    "example/godomon/assets/**/Navigale.png",
    "example/godomon/assets/**/Negagen.png",
    "example/godomon/assets/**/Nemesusa.png",
    "example/godomon/assets/**/Nymfushia.png",
    "example/godomon/assets/**/Oppwold.png",
    "example/godomon/assets/**/Petalcher.png",
    "example/godomon/assets/**/Plantid.png",
    "example/godomon/assets/**/Plushion.png",
    "example/godomon/assets/**/Pompet.png",
    "example/godomon/assets/**/Pomprim.png",
    "example/godomon/assets/**/Pourka.png",
    "example/godomon/assets/**/Pubeta.png",
    "example/godomon/assets/**/Qwirm.png",
    "example/godomon/assets/**/Rainther.png",
    "example/godomon/assets/**/Raskit.png",
    "example/godomon/assets/**/Reaphid.png",
    "example/godomon/assets/**/Robustaur.png",
    "example/godomon/assets/**/Rockid(Fairy).png",
    "example/godomon/assets/**/Rockid(Normal).png",
    "example/godomon/assets/**/Rockid(Steel).png",
    "example/godomon/assets/**/Rocotton.png",
    "example/godomon/assets/**/Roogilist.png",
    "example/godomon/assets/**/Rootsy.png",
    "example/godomon/assets/**/Sanda.png",
    "example/godomon/assets/**/Saurky.png",
    "example/godomon/assets/**/Scalamber.png",
    "example/godomon/assets/**/Scarambi.png",
    "example/godomon/assets/**/Scaropti.png",
    "example/godomon/assets/**/Scavengila.png",
    "example/godomon/assets/**/Scragorge.png",
    "example/godomon/assets/**/Scruffian.png",
    "example/godomon/assets/**/Searpent.png",
    "example/godomon/assets/**/Shadeleon.png",
    "example/godomon/assets/**/Shockfull.png",
    "example/godomon/assets/**/Silennium.png",
    "example/godomon/assets/**/Sizzly.png",
    "example/godomon/assets/**/Skelleks.png",
    "example/godomon/assets/**/Sligment.png",
    "example/godomon/assets/**/Smoald.png",
    "example/godomon/assets/**/Snagatoof.png",
    "example/godomon/assets/**/Snome.png",
    "example/godomon/assets/**/Snowly.png",
    "example/godomon/assets/**/Sorcepher.png",
    "example/godomon/assets/**/Spikonsia.png",
    "example/godomon/assets/**/Spiralusk.png",
    "example/godomon/assets/**/Squizard.png",
    "example/godomon/assets/**/Strivane.png",
    "example/godomon/assets/**/Strunk.png",
    "example/godomon/assets/**/Stubhorn(Fairy).png",
    "example/godomon/assets/**/Stubhorn(Normal).png",
    "example/godomon/assets/**/Stubhorn(Steel).png",
    "example/godomon/assets/**/Subyss.png",
    "example/godomon/assets/**/Sycoral.png",
    "example/godomon/assets/**/Synopede.png",
    "example/godomon/assets/**/Thissblade.png",
    "example/godomon/assets/**/Tidoral.png",
    "example/godomon/assets/**/Timberry.png",
    "example/godomon/assets/**/Tindursa.png",
    "example/godomon/assets/**/Trablur.png",
    "example/godomon/assets/**/Triastick.png",
    "example/godomon/assets/**/Tuffettry.png",
    "example/godomon/assets/**/Turbatic.png",
    "example/godomon/assets/**/Umbreeze.png",
    "example/godomon/assets/**/Upspark.png",
    "example/godomon/assets/**/Vamingo.png",
    "example/godomon/assets/**/Varmot.png",
    "example/godomon/assets/**/Velamour.png",
    "example/godomon/assets/**/Viscolor.png",
    "example/godomon/assets/**/Vitail.png",
    "example/godomon/assets/**/Vizitid.png",
    "example/godomon/assets/**/Winkami.png",
    "example/godomon/assets/**/Winkap.png",
    "example/godomon/assets/**/Winkip.png",
    "example/godomon/assets/**/Wyntry.png",
    "example/godomon/assets/**/Zapoteur.png",
]
SPDX-FileCopyrightText = "2020, Magiscarf <https://www.deviantart.com/magiscarf/art/Sprite-Sheet-w-Backsprites-w-Shinies-WIP-834432339>"
SPDX-License-Identifier = "CC-BY-NC-SA-3.0"
